versions: 0.2

phases:

  pre_build:
  
    commands:
    
      - npm install
      
  build:
  
    commands:
    
      - npm run build
      
artifacts:

  files:
  
    - '**/*'
    
  dicards_paths: no
  
  base-directory: dist/project
